# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 16:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepassementReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zone', models.IntegerField(default=999)),
                ('resultat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_exp', models.IntegerField(default=None)),
                ('delta', models.IntegerField()),
                ('mn', models.IntegerField(default=None, null=True)),
                ('mx', models.IntegerField(default=None, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='IndiceCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField()),
                ('indice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IndiceComVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mep', models.IntegerField()),
                ('detail', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('is_source', models.BooleanField(default=False)),
                ('commentaire', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSourceRaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrun', models.IntegerField(default=999)),
                ('pol', models.CharField(max_length=10)),
                ('ech', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('is_default_source', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='tsr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.TypeSourceRaster'),
        ),
        migrations.AddField(
            model_name='indicecom',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster.Source'),
        ),
        migrations.AddField(
            model_name='indicecom',
            name='version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.IndiceComVersion'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.Source'),
        ),
        migrations.AddField(
            model_name='depassementreg',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster.Source'),
        ),
    ]
