# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_web_mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('api_mod', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.Api_web_mod')),
            ],
        ),
        migrations.CreateModel(
            name='Fine_echelle_mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('dirFine', models.CharField(default='/home/previ/raster_source/domaines_fine/3857', max_length=200)),
                ('dirFineCustom', models.CharField(default='/home/previ/raster_source/domaines_fine/3857/custom', max_length=200)),
                ('raster_prefix', models.CharField(default='AURA', max_length=200)),
                ('hd_dest', models.CharField(default='', max_length=200)),
                ('hd_path', models.CharField(default='/var/www/html/hd/', max_length=200)),
                ('hd_val_path', models.CharField(default='/var/www/html/hd/val', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Previ_mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('DIR_RASTERS', models.CharField(default='/home/previ/raster_source', max_length=200)),
                ('DIR_RASTERS_GLOB', models.CharField(default='/home/previ/raster_source', max_length=200)),
                ('raster_prefix', models.CharField(default='AURA', max_length=200)),
                ('hd_dest', models.CharField(default='', max_length=200)),
                ('hd_path', models.CharField(default='/var/www/html/hd/', max_length=200)),
                ('hd_val_path', models.CharField(default='/var/www/html/hd/val', max_length=200)),
                ('basse_def_path', models.CharField(default='/var/www/html/basse_def/', max_length=200)),
                ('basse_def_val_path', models.CharField(default='/var/www/html/basse_def/val/', max_length=200)),
                ('basse_def_url', models.CharField(default='', max_length=200)),
                ('basse_def_url_val_path', models.CharField(default='', max_length=200)),
                ('launch_smile_prod', models.CharField(default='', max_length=200)),
                ('launch_smile_preprod', models.CharField(default='', max_length=200)),
                ('mylogs', models.CharField(default='/var/www/html/mylogs.txt', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20)),
                ('domaine', models.CharField(default='', max_length=20)),
                ('user', models.CharField(default='', max_length=20)),
                ('dir', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='dateprev',
            name='date_prev',
            field=models.IntegerField(default=1521759600),
        ),
        migrations.AlterField(
            model_name='prev',
            name='date_prev',
            field=models.IntegerField(default=1521759600),
        ),
        migrations.AddField(
            model_name='previ_mod',
            name='export_scp',
            field=models.ManyToManyField(to='raster.RemoteMachine'),
        ),
        migrations.AddField(
            model_name='context',
            name='fine_mod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.Fine_echelle_mod'),
        ),
        migrations.AddField(
            model_name='context',
            name='previ_mod',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.Previ_mod'),
        ),
    ]
