# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0002_auto_20180323_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicoPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='remotemachine',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.DicoPath'),
        ),
    ]
