# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0003_auto_20170616_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceraster',
            name='daterun',
        ),
        migrations.AddField(
            model_name='sourceraster',
            name='intrun',
            field=models.IntegerField(default=999),
        ),
    ]
