# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0003_auto_20180323_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicopath',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
