# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0004_auto_20170616_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date_previs', models.DateField(default=None)),
                ('is_source', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='SourceRaster',
            new_name='TypeSourceRaster',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='daterun',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='ech',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='pol',
        ),
        migrations.AddField(
            model_name='expertise',
            name='date_valid',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='source',
            name='id_type_source_raster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster.TypeSourceRaster', verbose_name='id du type source'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='id_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.Source', verbose_name='id de la source'),
        ),
    ]
