# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0005_auto_20170616_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
