# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0005_auto_20180323_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previ_mod',
            name='export_scp',
        ),
    ]
