# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0006_source_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesourceraster',
            name='is_default_source',
            field=models.BooleanField(default=False),
        ),
    ]
