# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0006_remove_previ_mod_export_scp'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
