# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-23 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0007_context_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='previ_mod',
            name='machines',
            field=models.ManyToManyField(to='raster.RemoteMachine'),
        ),
    ]
