# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0007_typesourceraster_is_default_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
