# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0008_previ_mod_machines'),
    ]

    operations = [
        migrations.CreateModel(
            name='BassinGrenoblois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=200)),
                ('user', models.CharField(default='', max_length=200)),
                ('db', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('table', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='context',
            name='api_mod',
        ),
        migrations.AlterField(
            model_name='context',
            name='fine_mod',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raster.Fine_echelle_mod'),
        ),
        migrations.AlterField(
            model_name='dateprev',
            name='date_prev',
            field=models.IntegerField(default=1522015200),
        ),
        migrations.AlterField(
            model_name='fine_echelle_mod',
            name='dirFine',
            field=models.CharField(default='/home/previ/raster_source/domaines_fine/3857', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fine_echelle_mod',
            name='dirFineCustom',
            field=models.CharField(default='/home/previ/raster_source/domaines_fine/3857/custom', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fine_echelle_mod',
            name='hd_dest',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fine_echelle_mod',
            name='hd_path',
            field=models.CharField(default='/var/www/html/hd/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fine_echelle_mod',
            name='hd_val_path',
            field=models.CharField(default='/var/www/html/hd/val', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fine_echelle_mod',
            name='raster_prefix',
            field=models.CharField(default='AURA', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prev',
            name='date_prev',
            field=models.IntegerField(default=1522015200),
        ),
        migrations.DeleteModel(
            name='Api_web_mod',
        ),
        migrations.AddField(
            model_name='context',
            name='bassin_grenoblois',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='raster.BassinGrenoblois'),
        ),
    ]
