# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0008_auto_20170616_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='date_previs',
        ),
    ]
