# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0009_remove_source_date_previs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id_type_source_raster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raster.TypeSourceRaster'),
        ),
    ]
