# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0009_auto_20180326_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='bassin_grenoblois',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raster.BassinGrenoblois'),
        ),
        migrations.AlterField(
            model_name='context',
            name='fine_mod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raster.Fine_echelle_mod'),
        ),
    ]
