# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0010_auto_20170616_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='id_type_source_raster',
        ),
        migrations.AddField(
            model_name='source',
            name='type_source_raster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.TypeSourceRaster', verbose_name='id fk'),
        ),
    ]
