# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0010_auto_20180326_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='api_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='context',
            name='previ_active',
            field=models.BooleanField(default=False),
        ),
    ]
