# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0012_auto_20180326_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicopath',
            name='suffixe',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dateprev',
            name='date_prev',
            field=models.IntegerField(default=1522188000),
        ),
        migrations.AlterField(
            model_name='prev',
            name='date_prev',
            field=models.IntegerField(default=1522188000),
        ),
    ]
