# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0012_auto_20170616_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2017, 6, 20, 15, 46, 13, 613810)),
        ),
    ]
