# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0013_source_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesourceraster',
            name='statut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='id_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='raster.TypeSourceRaster', verbose_name='id de la source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2017, 6, 21, 14, 41, 56, 935174)),
        ),
    ]
