# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0014_previ_mod_public_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateprev',
            name='date_prev',
            field=models.IntegerField(default=1524002400),
        ),
        migrations.AlterField(
            model_name='prev',
            name='date_prev',
            field=models.IntegerField(default=1524002400),
        ),
    ]
