# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0014_auto_20170621_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='type_source_raster',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
